package com.newcastle_university_group1.student_management_system_backend.service.impl;

import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import com.newcastle_university_group1.student_management_system_backend.entity.CourseworkStudent;
import com.newcastle_university_group1.student_management_system_backend.mapper.CourseworkStudentMapper;
import com.newcastle_university_group1.student_management_system_backend.service.ICourseworkStudentService;
import org.springframework.stereotype.Service;

@Service
public class CourseworkStudentServiceImpl extends ServiceImpl<CourseworkStudentMapper, CourseworkStudent> implements ICourseworkStudentService {
}
